#!/bin/bash

# bash x.sh /dev/sda 6

if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]]; then
    echo "This script must be called passing the following arguments:"
    echo "1) Device"
    echo "2) Second partition (swap) size (in GiB)"
    echo
    echo "Example"
    echo "./1a-partition /dev/sda 6"
    exit 1
fi

END_BOOT_PART=$(sudo parted -sa optimal -- "$1" print | grep boot | awk '{print $3}' | grep -o '[0-9]\+')

# end_second_partition=$(($2 + $3))
SIZE_IN_MB=$(($2 * 1024))
END_SECOND_PARTITION=$(($END_BOOT_PART + $SIZE_IN_MB))

# echo "First: size $2 GiB, End: $2 GiB"
echo "Second: size $2 GiB, End: $END_SECOND_PARTITION MB"

sudo parted -sa optimal -- "$1" \
rm 2 \
mkpart swap linux-swap "$END_BOOT_PART"MB "$END_SECOND_PARTITION"MB set 2 swap on \
mkpart system btrfs "$END_SECOND_PARTITION"MB -1 \
print