#!/bin/bash

# bash x.sh /dev/sda 5 6

if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]]; then
    echo "This script must be called passing the following arguments:"
    echo "1) Device"
    echo "2) First partition (boot) size (in GiB)"
    echo "3) Second partition (swap) size (in GiB)"
    echo
    echo "Example"
    echo "./1a-partition /dev/sda 5 6"
    exit 1
fi

end_second_partition=$(($2 + $3))

echo "First: size $2 GiB, End: $2 GiB"
echo "Second: size $3 GiB, End: $end_second_partition GiB"

sudo parted -sa optimal -- "$1" \
mklabel gpt \
mkpart boot fat32 0% "$2"GiB set 1 boot on \
mkpart swap linux-swap "$2"GiB "$end_second_partition"GiB set 2 swap on \
mkpart system btrfs "$end_second_partition"GiB -1 \
print