#!/bin/bash

# ./1b-format.sh /dev/sda

if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

if [[ -z $1 ]]; then
    cat <<- _EOT_
    This script must be called passing the device that will be formated"
    
    Example
    $0 /dev/sda
	_EOT_

    exit 1
fi

mkfs.fat -F32 "$1"1

lsblk "$1"1 -f

mkswap "$1"2
swapon "$1"2

lsblk "$1"2 -f

mkfs.btrfs -f "$1"3

lsblk "$1"3 -f