#!/bin/bash

# $1 = system partition, $2 = mounted folder
#example:
#./2-create-subvols-and-mount.sh /dev/sda3 /mnt

if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

if [[ -z $1 ]]; then
    cat << _EOT_
This script must be called passing the following arguments:
1) System partition
2) Folder where it will be mounted

Example:
$0 /dev/sda3 /mnt
_EOT_

    exit 1
fi

mount -v "$1" "$2"
cd "$2" || exit

btrfs subvolume create @
btrfs subvolume create @home
btrfs subvolume create @etc
mkdir -v @etc/work
mkdir -v @etc/upper
btrfs subvolume create @bkp_off
mkdir -v -p var/_btrbk_snap
btrfs subvolume create var/@flatpak
btrfs subvolume create var/@snap
btrfs subvolume create var/@main
btrfs subvolume create var/@plex
btrfs subvolume create var/@portables
btrfs subvolume create var/@machines
btrfs subvolume create @root_user
btrfs subvolume create @games
btrfs subvolume create @steam
btrfs subvolume create @flatpak_home
btrfs subvolume create @flatpak
btrfs subvolume create @snap
mkdir -v btrbk_snapshots

tree

cd - || exit
umount -v "$2"