#!/bin/bash

# ./4-configure-system-step1.sh /mnt Laptop

if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

if [[ -z $1 ]]; then
    cat <<- _EOT_
		This script must be called passing the following arguments:
        1) Name used for localhost

		Example:
		$0 Laptop
	_EOT_

    exit 1
fi

ln -vsf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

hwclock --systohc -v

sed -i 's/#pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/g' /etc/locale.gen
grep "pt_BR.UTF-8" /etc/locale.gen

locale-gen

echo LANG=pt_BR.UTF-8 | tee -a /etc/locale.conf
cat /etc/locale.conf

echo KEYMAP=br-abnt2 | tee -a /etc/vconsole.conf
cat /etc/vconsole.conf

echo "$1" | tee -a /etc/hostname

echo '127.0.0.1  localhost' | tee -a /etc/hosts
echo '::1        localhost' | tee -a  /etc/hosts
echo "127.0.1.1  $1.localdomain $1" | tee -a /etc/hosts

sed -i 's/#Color/Color/g' /etc/pacman.conf
sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 5/g' /etc/pacman.conf
sed -zi 's/#\[multilib\]\n#Include = \/etc\/pacman.d\/mirrorlist/\[multilib\]\nInclude = \/etc\/pacman.d\/mirrorlist/g' /etc/pacman.conf
cat /etc/pacman.conf

sed -i 's/MODULES=()/MODULES=(btrfs)/g' /etc/mkinitcpio.conf
cat /etc/mkinitcpio.conf

useradd -mG wheel jayson

grep jayson /etc/passwd
grep jayson /etc/group

chown -v jayson:jayson -R /home/jayson

echo "Defina a senha root"
passwd
echo "Defina a senha do usuário jayson"
passwd jayson

EDITOR=nano visudo


# export -f config_system
# arch-chroot "$1" /bin/bash -c "config_system"