#!/bin/bash

mkdir -v -p ~/.local/share
mv -v ~/.oh-my-zsh ~/.local/share/oh-my-zsh

mkdir -v -p ~/.local/state/zsh
mv -v ~/.zsh_history ~/.local/state/zsh/history

mkdir -v -p ~/.config/zsh
mv -v ~/.zshrc ~/.config/zsh/.zshrc