#!/bin/bash

if [[ $EUID -eq 0 ]]; then
	echo "This script must be executed as a normal user (NOT ROOT)"
	exit 1
fi

if [[ -z "$1" ]]; then
    cat <<- _EOT_
		This script must be called passing the parent folder as argument.

		Example:
		$0 /home/jayson/
	_EOT_

	exit 1
fi

export XDG_DATA_HOME="$HOME/.local/share"
echo "XDG_DATA_HOME=${XDG_DATA_HOME}"
export XDG_CONFIG_HOME="$HOME/.config"
echo "XDG_CONFIG_HOME=${XDG_CONFIG_HOME}"

cd "$1".dotfiles || exit
pwd
./install-profile home
