#!/bin/sh

export XDG_DATA_HOME="$HOME/.local/share"
echo "XDG_DATA_HOME=${XDG_DATA_HOME}"
export XDG_CONFIG_HOME="$HOME/.config"
echo "XDG_CONFIG_HOME=${XDG_CONFIG_HOME}"

cd -v ~/.dotfiles
./install-profile home
