#!/bin/bash

#./enter-update-system.sh /dev/sda4

if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

RESET=$(cat reset_done)

echo "RESET = $RESET"

if [[ $RESET = "TRUE" ]]; then
	echo "System was factory-reset. You need to reboot first to continue using"
	exit 1
fi

DEPLOYED=$(cat deployed)

echo "DEPLOYED = $DEPLOYED"

if [[ $DEPLOYED = "TRUE" ]]; then
	echo "Updated system was already deployed. You need to reboot first to do a new change on the system"
	exit 1
fi

btrbk -S --progress run

if [[ -d /btr_pool/@current ]]; then
	btrfs subvolume delete /btr_pool/@current
	btrfs subvolume delete /btr_pool/var/@main_current
fi

mv -v /btr_pool/@ /btr_pool/@current
mv -v /btr_pool/var/@main /btr_pool/var/@main_current

if [[ -d /btr_pool/@ ]]; then
	echo "Error: subvolume @ exists or was not removed before"
	echo " Remove it first and reexecute this script"
	exit 1
fi

if [[ -d /btr_pool/var/@main ]]; then
	echo "Error: subvolume var/@main exists or was not removed before"
	echo " Remove it first and reexecute this script"
	exit 1
fi

btrfs subvolume snapshot -r /btr_pool/@rw /btr_pool/@
btrfs subvolume snapshot /btr_pool/var/@main_rw /btr_pool/var/@main

./clean-etc

mount -vB true_file deployed