#!/bin/bash

#./enter-update-system.sh /dev/sda3


if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

if [[ -z "$1" ]]; then
	echo "This script must be called passing system partition. Example:"
	echo "./enter-update-system /dev/sda3"
	exit 1
fi

DEPLOYED=$(cat deployed)

echo "DEPLOYED = $DEPLOYED"

if [[ $DEPLOYED = "TRUE" ]]; then
	echo "Updated system was already deployed. You need to reboot first to do a new change on the system"
	exit 1
fi

SSD_options="noatime,compress=zstd,commit=120"

mount -v "$1" -o $SSD_options,subvol=/@rw /mnt

/bin/arch-chroot /mnt bash << _EOT_
mount -va
umount -vR /etc
umount -vR /var
hostname ArchVM-Update
_EOT_

mount -v "$1" -o $SSD_options,subvol=/var/@main_rw /mnt/var
mount -v "$1" -o $SSD_options,subvol=@snap /mnt/var/snap
mount -v "$1" -o $SSD_options,subvol=@flatpak /mnt/var/lib/flatpak
mount -v "$1" -o $SSD_options,subvol=/var/@portables var/lib/portables
mount -v "$1" -o $SSD_options,subvol=/var/@machines var/lib/machines

mount -v --bind /btr_pool/@bkp_off/cache /mnt/var/cache
mount -v --bind /btr_pool/@bkp_off/tmp /mnt/var/tmp

findmnt -R /mnt -t btrfs,vfat,overlay

/bin/arch-chroot /mnt /bin/zsh

cp -v /boot/grub/grub.cfg /boot/grub/grub.cfg.bak
sed -i 's/@rw/@/g' /boot/grub/grub.cfg
grep --color @ /boot/grub/grub.cfg

umount -vR /mnt