#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

btrbk -S --progress run

cd /btr_pool || return
pwd

# btrfs subvolume delete @last
# mv -v @ @last
btrfs subvolume delete @rw
btrfs subvolume snapshot @base_system @rw
btrfs subvolume snapshot -r @rw @

cd var || return
pwd

# btrfs subvolume delete @main_last
# mv -v @main @main_last
btrfs subvolume delete @main_rw
btrfs subvolume snapshot @main_base @main_rw
btrfs subvolume snapshot @main_rw @main

./clean-etc