#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be executed as SUDO or ROOT"
	exit 1
fi

DEPLOYED=$(cat deployed)

echo "DEPLOYED = $DEPLOYED"

if [[ $DEPLOYED = "TRUE" ]]; then
	echo "Updated system was already deployed. You need to reboot first to do a new change on the system"
	exit 1
fi

RESET=$(cat reset_done)

echo "RESET = $RESET"

if [[ $RESET = "TRUE" ]]; then
	echo "System was factory-reset. You need to reboot first to continue using"
	exit 1
fi

btrbk --progress run

LAST_DIR=$(pwd)

cd /btr_pool || return
pwd

if [[ -d @current ]]; then
	btrfs subvolume delete @current
fi

if [[ -d var/@main_current ]]; then
	btrfs subvolume delete var/@main_current
fi

if [[ -d @ ]]; then
	mv -v @ @current
fi

if [[ -d var/@main ]]; then
	mv -v var/@main var/@main_current
fi

btrfs subvolume delete @rw
btrfs subvolume snapshot @base_system @rw
btrfs subvolume snapshot -r @rw @

cd var || return
pwd

btrfs subvolume delete @main_rw
btrfs subvolume snapshot @main_base @main_rw
btrfs subvolume snapshot @main_rw @main

cd "$LAST_DIR" || return
pwd

./clean-etc

mount -vB true_file reset_done