#!/bin/bash

#$1 = boot partition, "$2" = system partition, $3 = mounted folder
#example:
#./2-create-subvols-and-mount.sh /dev/sda1 /dev/sda3 /mnt

SSD_options="noatime,compress=zstd,commit=120"

mount -v "$2" -o $SSD_options,subvol=/@rw $3
cd "$3" || exit

if [ ! -d "btr_pool" ]; then
	CREATE_DIRS=true
fi

if [ "$CREATE_DIRS" = true ]; then
	mkdir -v {btr_pool,boot,home,root,var}
fi

mount -v "$2" -o $SSD_options,subvol=/ btr_pool
mount -v "$1" boot
mount -v "$2" -o $SSD_options,subvol=/var/@main_rw var
mount -v "$2" -o $SSD_options,subvol=@home home

if [ "$CREATE_DIRS" = true ]; then
	mkdir -v -p home/jayson/{.cache,.var,.local,Downloads,Games}
	mkdir -v home/jayson/.var/app
	mkdir -v -p home/jayson/.local/share/Steam
fi

mount -v "$2" -o $SSD_options,subvol=@games home/jayson/Games
mount -v "$2" -o $SSD_options,subvol=@steam home/jayson/.local/share/Steam
mount -v "$2" -o $SSD_options,subvol=@flatpak_home home/jayson/.var/app

if [ "$CREATE_DIRS" = true ]; then
	mkdir -v btr_pool/@bkp_off/{downloads,cache_home}
	mkdir -v btr_pool/@bkp_off/{cache,tmp,downloads_root,cache_root}
fi

mount -v --bind btr_pool/@bkp_off/downloads home/jayson/Downloads
mount -v --bind btr_pool/@bkp_off/cache_home home/jayson/.cache

if [ "$CREATE_DIRS" = true ]; then
	mkdir -v var/{cache,tmp,lib,snap}
	mkdir -v var/lib/flatpak
fi

mount -v "$2" -o $SSD_options,subvol=@snap var/snap
mount -v "$2" -o $SSD_options,subvol=@flatpak var/lib/flatpak

mount -v --bind btr_pool/@bkp_off/cache var/cache
mount -v --bind btr_pool/@bkp_off/tmp var/tmp

mount -v "$2" -o $SSD_options,subvol=@root_user root

if [ "$CREATE_DIRS" = true ]; then
	mkdir -v root/{.cache,Downloads}
fi

mount -v --bind btr_pool/@bkp_off/downloads_root root/Downloads
mount -v --bind btr_pool/@bkp_off/cache_root root/.cache

cd ~ || exit

findmnt -R "$3"
