#!/bin/bash



cd /btr_pool || return
pwd

mv -v @ @rw
btrfs subvolume snapshot -r @rw @base_system
btrfs subvolume snapshot -r @rw @

mv -v var/@main var/@main_rw
btrfs subvolume snapshot -r var/@main_rw var/@main_base
btrfs subvolume snapshot -r var/@main_rw var/@main


ORIGINAL_LINE=$(grep "/ " /etc/fstab)
# shellcheck disable=SC2116
FINAL_LINE=$(echo "${ORIGINAL_LINE//rw/ro}")
sed -i "s&${ORIGINAL_LINE}&${FINAL_LINE}&g" /etc/fstab